### ISSUE TITLE
Agoo dumps core on malformed SDL

### ISSUE THREAD

**Issue by jjw** [ohler55/agoo#107]
Certain SDL syntax errors will cause Agoo to dump core

Reproduce on Ubuntu 20.02.4 LTS by downloading `agoo/example/graphql/song.{rb,graphql}` and run as follows
```
sed -i 's/!)/!/' song.graphql  # introduce syntax error in first line of Query by deleting closing parenthesis
ruby song.rb >log.txt 2>&1
Aborted
```
[log.txt](https://github.com/ohler55/agoo/files/8110014/log.txt)

Cheers,
  Jerry

**Comment by ohler55** [comment]
I'll get it fixed. With luck, in the next couple of days.

**Comment by ohler55** [comment]
Please try the fix-bad-sdl-crash branch.

**Comment by ohler55** [comment]
Released. Thank for reporting the issue.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by jjw** [comment]
Sorry, should have said that I'm running the gem so I haven't been able to
test by cloning the repo.  I'll take your word for it though :-) so yes,
please close.

Thanks,
  Jerry
