### ISSUE TITLE
Static asset with space in filename

### ISSUE THREAD

**Issue by smithtim** [ohler55/agoo#114]
I can't get agoo to serve a static asset with a space in the filename.  For example, `foo bar.html`.  When I go to `http://localhost:6464/foo%20bar.html`, I get a 404.  Filenames without spaces work fine.

**Comment by ohler55** [comment]
I'll get that fixed. I'm surprised that bug has been around for so long.

**Comment by ohler55** [comment]
Please try the space-names branch. I believe that fixes the issue. A unit test was added for it as well.

**Comment by smithtim** [comment]
That works, thanks!

**Comment by ohler55** [comment]
Released v2.15.3 with the fix.
