### ISSUE TITLE
Static .txt files are not served with utf-8 encoding

### ISSUE THREAD

**Issue by odinhb** [ohler55/agoo#118]
I put some emojies in a .txt file in the `/public` directory:

```txt
# emojies.txt
👏👏 👀 haha
```

```rb
# somewhere in my server script

Agoo::Server.init(
  3000,
  "/public",
  {
    root_first: true,
  },
)
```

When I go to `localhost:3000/emojies.txt` in my browser I get this:

```
ðŸ‘ðŸ‘ ðŸ‘€ haha
```

I think we should default to sending the header `Content-Type: text/plain; charset=utf-8` instead of just `Content-Type: text/plain`

**Comment by ohler55** [comment]
That's a reasonable request. I'll make the change.

**Comment by ohler55** [comment]
Please try the "mime-txt-utf8" branch.

**Comment by ohler55** [comment]
I think for Ruby files the receiver decides although for display it might make sense. I was hesitant to get too carried away and cause issue by over specifying. Ruby is probably safe though. Can you try a ruby file and see how the browser handles it?

**Comment by odinhb** [comment]
Firefox seems to not handle .rb with emojies without the charset:

```rb
# hax.rb
puts "get hacked! >:D"

puts "emojiii: 🚀🚀🚀"
```

![image](https://user-images.githubusercontent.com/49036561/228967745-d66163db-7499-4db9-bdbb-e555ff4a3ac0.png)

I can appreciate you wanting to be careful, so I took a look at what github does when you request an .rb file:
![image](https://user-images.githubusercontent.com/49036561/228968568-21460d22-db82-4a2e-82a8-1825cfce4bec.png)
![image](https://user-images.githubusercontent.com/49036561/228968635-95b461a8-0fff-4fb1-907f-50cedfcb50d0.png)

I don't know if you happen to have any .rb files with emoji in them :sweat_smile:

I think the absolute safest thing to do here would be to run charset detection on the file before deciding what to put in the header, and defaulting to utf8 since it is so ubiquitous and backwards compatible with ascii.

This kind of detection is probably overkill though.

**Comment by ohler55** [comment]
The issue isn't emoji but other unicode characters for languages such as Japanese. I'll add to Ruby and other language files on the list.

**Comment by ohler55** [comment]
Pushed the changes for the other text file types.

**Comment by ohler55** [comment]
Released
