### ISSUE TITLE
502 via nginx proxy_pass

### ISSUE THREAD

**Issue by sergeymavrin** [ohler55/agoo#126]
Have interesting behaviour - if I make direct request to agoo - it's succeeded, but when make a request via nginx - get 502.
In this request long reqeust is exequting to mysql (about 15-20 seconds).
![1](https://github.com/ohler55/agoo/assets/43964130/9d098588-6642-49c0-819f-00c03e7653b4)
and it seems, that agoo initiate close connection due to #define CON_TIMEOUT              10.0
Can you help me to understand the difference between direct call and via nginx proxy_pass (proxy_send_timeout, proxy_read_timeout and proxy_connect_timeout all set to 1800s) and can I tune this value?

**Comment by ohler55** [comment]
As you probably saw in the code it is not currently configurable. That is something I can add though.

**Comment by sergeymavrin** [comment]
That would be amazing to have an option in Server.init method )
But the question - why direct request to Agoo not catching 502 - is still interesting

**Comment by ohler55** [comment]
The "rackup_handler" branch has an option for setting the connection_timeout.

I'm not sure about the nginx issue. If you have an environment setup for testing that can you let me know what the request from nginx looks like?
