### ISSUE TITLE
TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by bendangelo** [ohler55/agoo#127]
Running Rails 7.1.6 and Ruby 3.3.0.

I get no error in the logs, this is shown in the browser.

I also get these deprecation warnings:

Rack::Handler is deprecated and replaced by Rackup::Handler
/home/bendangelo/.rvm/gems/ruby-3.3.0/gems/agoo-2.15.8/lib/rack/handler/agoo.rb:180: warning: Calling Rackup::Handler.register with a string is deprecated, use the class/module itself.
RACK_HANDLER is deprecated, use RACKUP_HANDLER.

Edit: Tested in Ruby 3.2.2 and the same error.

**Comment by ohler55** [comment]
I've got a couple of fixes due. I'll add this to the list. I hope to address then once back from vacation.

**Comment by bendangelo** [comment]
I found the issue. It's  `gem "rack-mini-profiler"`. I'm using version 3.3.0

**Comment by ohler55** [comment]
Should have been fixed back in February.

**Comment by bendangelo** [comment]
fixed
