### ISSUE TITLE
Out of curiousity would anything have been lost or gained by using ABI, or FFI, or *.SO over the current API method of directly calling in the Ruby C file headers?

### ISSUE THREAD

**Issue by shehackedyou** [ohler55/agoo#129]
I'm curious because I have been watching this project a long time, experimenting with it to learn more about Rack, and I am interested in doing some of my own direct work with the Ruby source. And would it just be advantageous to package Ruby headers and source, or compile it into a *.so? FFI?

Are there any major drawacks to any of these proposed solutions?

**Comment by ohler55** [comment]
When I started out there was only one real option. That is no longer true but I haven't spent the time to compare other choices. I would be interested in anything you find out though.

**Comment by shehackedyou** [comment]
Okay, yeah I plan to experiment with each and see the results then. I will inform, Ill write about it and send you the link. 

I appreciate the time you took to respond to me. Really love this project, it changed the way I think about Rack and Rails so much. Was a huge breakthrough for me; thanks for that.

**Comment by ohler55** [comment]
I am curious, how did it change your views on Rack and Rails?

**Comment by shehackedyou** [comment]
Oh you broke my entire brain. It made me have to realize I didn't know
enough about Rack. Now all my Rails applications run way faster using a
custom Go server frontend.

I can't thank you enough. What is frustrating is I try to show this to
others like Mastodon developers but they are too close-minded, power-hungry
to even take a second to understand why I'm able to take their application
make a 1 line change a get 8x the speed at every type of load.

And when they are like, well, there is no interest in this change. Its
like, uhh, because you don't get how rack and rails integrate then,..

But I can't tell you how much I appreciate it, it gave me new avenues to
learn about Ruby, its relation to C, got me writing my own Ruby version,
rack servers, etc.

Thank you, from the bottom of my heart <3
