### ISSUE TITLE
Compilation on Mac requires OS X 10.12?

### ISSUE THREAD

**Issue by jdickey** [ohler55/agoo#14]
System: mid-2011 iMac, 3.1 GHz Intel Core i5, OS X 10.11.6

Running `gem install agoo` fails at [line 365 of `log.c`](https://github.com/ohler55/agoo/blob/develop/ext/agoo/log.c#L365), where the constant `CLOCK_REALTIME` is reported as nonexistent. The discussion on [this SO question for an identically-manifesting error](https://stackoverflow.com/q/5167269/1372767) eventually converges on a consensus that Xcode 8 is required for that function, and thus OS X 10.12 (which is required to run Xcode 8).

It Would Be Very Nice If the OS X version restriction was noted prominently in the `README`. It would be even nicer (though unexpected) if anyone has ideas for a workaround that would support those of us thus far unable to migrate to (High) Sierra.

Output from running `gem install agoo` follows:
```
Building native extensions. This could take a while...
ERROR:  Error installing agoo:
	ERROR: Failed to build gem native extension.

    current directory: /Users/jeffdickey/src/ruby/the_app/tmp/gemset/gems/agoo-2.0.0/ext/agoo
/usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/bin/ruby -r ./siteconf20180501-36922-1lvt4wa.rb extconf.rb
creating Makefile
>>>>> Created Makefile for ruby version 2.5.1 on x86_64-darwin15 <<<<<

current directory: /Users/jeffdickey/src/ruby/the_app/tmp/gemset/gems/agoo-2.0.0/ext/agoo
make "DESTDIR=" clean

current directory: /Users/jeffdickey/src/ruby/the_app/tmp/gemset/gems/agoo-2.0.0/ext/agoo
make "DESTDIR="
compiling agoo.c
compiling base64.c
compiling ccache.c
compiling con.c
compiling debug.c
compiling dtime.c
compiling err.c
compiling error_stream.c
compiling hook.c
compiling http.c
compiling log.c
log.c:365:2: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &ts);
        ^
log.c:365:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts);
                      ^
1 warning and 1 error generated.
make: *** [log.o] Error 1

make failed, exit code 2
```

**Comment by ohler55** [comment]
Please try the 'clock' branch. If it works for you I'll make another release.

**Comment by jdickey** [comment]
Thanks; I'll give it a try shortly.

**Comment by ohler55** [comment]
Did the fix compile for you?

**Comment by jdickey** [comment]
Got sidetracked yesterday; trying it now.

**Comment by jdickey** [comment]
I was able to bundle my (very simple Hanami) app using Agoo while building a Docker image, but when I connect with a Web browser, I get an error message:

```
Rack::Lint::LintError: env variable SERVER_NAME has non-string value nil
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:20:in `assert'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:274:in `block in check_env'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:272:in `each'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:272:in `check_env'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:43:in `_call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/lint.rb:37:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/show_exceptions.rb:23:in `call'
	/usr/local/bundle/bundler/gems/agoo-296162d72a1e/lib/rack/handler/agoo.rb:47:in `start'
	/usr/local/bundle/bundler/gems/agoo-296162d72a1e/lib/rack/handler/agoo.rb:47:in `run'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:297:in `start'
	/usr/local/bundle/gems/hanami-1.2.0/lib/hanami/server.rb:43:in `start'
	/usr/local/bundle/gems/hanami-1.2.0/lib/hanami/cli/commands/server.rb:32:in `call'
	/usr/local/bundle/gems/hanami-1.2.0/lib/hanami/cli/commands/command.rb:85:in `call'
	/usr/local/bundle/gems/hanami-cli-0.2.0/lib/hanami/cli.rb:57:in `call'
	/usr/local/bundle/gems/hanami-1.2.0/bin/hanami:6:in `<top (required)>'
	bin/hanami:29:in `load'
	bin/hanami:29:in `<main>'
```

I've added an entry to the environment settings in my `docker-compose.yml` file and started it up. I can shell into the running container and see that the `SERVER_NAME` environment variable is set. But I get the output shown above. Any ideas?

**Comment by jdickey** [comment]
For context, I've had this app running with Webrick, Puma,  and Iodine in the same Ruby/Hanami/Docker environment, and they're all able to serve content Just Fine.

**Comment by ohler55** [comment]
I don't have any ideas yet but I do know what to check and would be very grateful if you will work with me on this. Can you share the code for the simple app with running instructions? The stack does give some some ideas of where to look though. Thank you for that.

So, the `SERVER_NAME` was set but the value is `nil`, correct? That could occur for one of two reasons. The `Host` in the request headers could be missing or the could be missing the port number. If you don't mind turning on logging we can see those values directly. If you can copy and past the request here I can see what should be made more tolerant on the Agoo side.

To make logging more verbose add this call at the top of the file.
```ruby
Agoo::Log.configure(dir: '',
		    console: true,
		    classic: true,
		    colorize: true,
		    states: {
		      INFO: true,
		      DEBUG: true,
		      connect: true,
		      request: true,
		      response: true,
		      eval: true,
		      push: true,
		    })
```

**Comment by ohler55** [comment]
I pushed a change that should always generate a string. Please pull and try. It may fix the issue immediately.

**Comment by ohler55** [comment]
BTW, I am very interested in improving Agoo so if you see anything you would like improved or added please let me know.

**Comment by ohler55** [comment]
Were you ever able to try the compile again?

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ohler55** [comment]
Seems dead. Closing.

**Comment by jdickey** [comment]
Sorry; I was dedicated elsewhere for the last few months. Go ahead and close this; if I still have any El Capitan dev machines by the time I get my current fires put out, I'll try again and open a new issue if warranted. Thanks for the patience and the hard work.
