### ISSUE TITLE
Compiling fails on Fedora 27 with gcc executable

### ISSUE THREAD

**Issue by strzibny** [ohler55/agoo#15]
Even though I have the right version of `gcc`:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
```
I cannot compile agoo:
```
$ gem install agoo
Building native extensions.  This could take a while...
ERROR:  Error installing agoo:
	ERROR: Failed to build gem native extension.

    current directory: /home/strzibny/.gem/ruby/gems/agoo-2.0.0/ext/agoo
/usr/bin/ruby -r ./siteconf20180504-3724-lxfgae.rb extconf.rb
creating Makefile
>>>>> Created Makefile for ruby version 2.4.3 on x86_64-linux <<<<<

current directory: /home/strzibny/.gem/ruby/gems/agoo-2.0.0/ext/agoo
make "DESTDIR=" clean
rm -f 
rm -f agoo.so  *.o  *.bak mkmf.log .*.time

current directory: /home/strzibny/.gem/ruby/gems/agoo-2.0.0/ext/agoo
make "DESTDIR="
gcc-7 -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -DPLATFORM_LINUX -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC -m64 -o agoo.o -c agoo.c
make: gcc-7: Command not found
make: *** [Makefile:243: agoo.o] Error 127

make failed, exit code 2
```
The build step expects gcc to be called `gcc-7` but on Fedora 27 it's just called `gcc`. I believe this would be the case for other systems as well.

**Comment by ohler55** [comment]
I had issues with earlier versions of gcc. Let me see if I can work around that.

**Comment by ohler55** [comment]
Checking travis now. It was the problem previously.

**Comment by ohler55** [comment]
Ok, fixed the travis issues so Makefile can be simply gcc instead of gcc-7.

**Comment by strzibny** [comment]
Cool, will there be a nice release?

**Comment by ohler55** [comment]
Released. Of course it is a nice release. :smile:

**Comment by strzibny** [comment]
Perfect, installation now works. Thank you!

**Comment by ohler55** [comment]
I do my best. Thanks for trying Agoo. If you have any requests please don't hesitate.

**Comment by strzibny** [comment]
I am just trying first Agoo with a completely new Rails app (`rails new ...`) and running it as:
```
$ rackup -r agoo -s agoo
I 2018/05/05 09:32:02.158460453 INFO: Agoo 2.0.2 listening on port 9292.
```
However going to `http://localhost:9292/` address I am getting:
```
ArgumentError: X-XSS-Protection is not a valid HTTP header key.
```
If I do the same with Puma server I get the famous "Yay! You’re on Rails!" page.

What am I missing?

**Comment by ohler55** [comment]
I have been supporting Rails with Oj for a while but have not written a rails app. Do you have an app I can try? Something else that might help would be seeing the log output. That would tell me if the error shows up on receiving or if some piece of middleware is generating that. I suspect I'll have to do some Rails tracing to see what is adding that.

```ruby
Agoo::Log.configure(dir: '',
		    console: true,
		    classic: true,
		    colorize: true,
		    states: {
		      INFO: true,
		      DEBUG: true,
		      connect: true,
		      request: true,
		      response: true,
		      eval: true,
		      push: true,
		    })
```

**Comment by ohler55** [comment]
The reason was 2 fold. X-XSS-Protection is not a registered header key which should have been fine but the check was not wrapped by checking the pedantic flag like it should have been.

**Comment by ohler55** [comment]
Agoo 2.0.3 released.

**Comment by strzibny** [comment]
The error is indeed gone, thanks for quick reply. Now I am facing another one:

```
$ rackup -r agoo -s agoo
I 2018/05/05 18:50:29.026798699 INFO: Agoo 2.0.3 listening on port 9292
double free or corruption (!prev)
Aborted (core dumped)
```

What happens is I see the welcome page correctly but after rendering the page agoo aborts the whole process. Btw I am using an empty app right now (`gem install rails && rails new my_new_app`).

**Comment by ohler55** [comment]
I appreciate your patience. I’m traveling now but will set up rails tomorrow and track that down.

**Comment by ohler55** [comment]
Fix and released as v2.0.4.

**Comment by strzibny** [comment]
The following should create CRUD for User model:
``
$ rails g scaffold User
$ rails db:migrate
$ rackup -r agoo -s agoo
```
Unfortunately `http://localhost:9292/users/new` path gives me the same static asset as the root (the Rails welcome page).

**Comment by ohler55** [comment]
I’ll try that. My guess is rails has a specific combination of path information. I see what that is and make sure it works.

**Comment by ohler55** [comment]
It was a path issue. The Rack spec has both a SCRIPT_NAME and a REQUEST_PATH. Apparently Rails does not combine them before evaluating. I'll with Agoo over to using the REQUEST_PATH. That worked but there is an authentication issue. I'll run though the CRUD pages and make sure everything works.

**Comment by strzibny** [comment]
Works. I will test later with a production app and if anything open new issues. Thanks!

**Comment by ohler55** [comment]
Thanks again for your patience.
