### ISSUE TITLE
CPU usage on "idle" server is big enough(?)

### ISSUE THREAD

**Issue by dm1try** [ohler55/agoo#23]
`puma` vs `agoo`
 Mac OS (CPU 4770HQ)
for 1 minute

![image](https://user-images.githubusercontent.com/486807/40813352-0c9c3ef4-6543-11e8-82e4-e1ff34a85ddf.png)
![image](https://user-images.githubusercontent.com/486807/40813388-402b435a-6543-11e8-8ed0-8aa9984f75dd.png)

**Comment by ohler55** [comment]
Maybe too aggressive in polling. I'll bring it down.

**Comment by ohler55** [comment]
I had a few TBDs waiting to get optimized. That was one of them. I'll escalate that and get something out next week. Will be out for the weekend but should be able to get to it Monday.

**Comment by ohler55** [comment]
You can try out the develop branch. I need to run some more tests and benchmarks but I think it is ready to go otherwise.

**Comment by dm1try** [comment]
yeah, it looks much better now, thank you!
![image](https://user-images.githubusercontent.com/486807/40848368-b12934fc-65c7-11e8-8a2d-586670644dd6.png)

**Comment by ohler55** [comment]
I think it might have made Agoo a bit faster as well. Have to run the benchmarks though.

**Comment by dm1try** [comment]
before I closed the issue, I ran some quick benchmarks using `wrk` and production app and did not found any significant difference(actually I was looking for a regression :))

**Comment by ohler55** [comment]
Good to know. I found that wrk could not keep up with static asset fetching. I use perfer instead. Wrk is fine for the Ruby parts though.
