### ISSUE TITLE
Bind to socket

### ISSUE THREAD

**Issue by bryanp** [ohler55/agoo#25]
I might have missed it in the code, but is it possible to bind to a socket instead of host + port?

**Comment by ohler55** [comment]
Currently the web server opens a socket to listen for connection requests. Are you proposing passing an open socket to the server and having the server listen on that socket instead of opening a new one? Interesting idea. How would you use that?

**Comment by bryanp** [comment]
I'm talking about binding to a unix socket, like in puma:

https://github.com/puma/puma/blob/b9a499d4c8542bfdc951d43e33e979a587a2878a/examples/config.rb#L75

**Comment by ohler55** [comment]
I might understand. Let me attempt to describe and see if I get the idea.

Instead of a simple socket open you would like to restrict the socket creation to a specific IP address or maybe open up as an SSL socket. If that is the case then there are two features to implement.
  1. restrict connections to a specific IP address
  2. Support HTTPS.

The first one I can implement fairly quickly. The support for SSL is planned but not immediately. Did I understand correctly?

**Comment by bryanp** [comment]
I don't think we're talking about the same thing. I'm also fully aware of how little I know about lower level things like this so I'll explain how I use Puma with the hope that it's more clear 😅

With Puma, I can bind to a local unix socket and setup a reverse proxy in Nginx like this:

```
upstream foo {
  server unix:///opt/apps/foo/puma.sock fail_timeout=0;
}
```

Can I accomplish the same thing with Agoo?

**Comment by ohler55** [comment]
I do some reading on setting up nginx. I had assumed that just putting in the address and port of the Agoo server would be sufficient to use Agoo with nginx as a reverse proxy.

**Comment by bryanp** [comment]
It is, but sometimes I opt for the unix socket approach for one reason or another. Not a huge problem if you don't want to support in agoo, I think it already serves the majority use case.

**Comment by ohler55** [comment]
After a little research I understand what you are looking for. Basically using Unix domain or named sockets. It is a good feature to add. I'll get that implemented with some unit tests. Would you be willing to try it with nginx when it is ready?

**Comment by bryanp** [comment]
Absolutely! I'm following this project pretty closely now, so let me know how I can help.

**Comment by ohler55** [comment]
Okay, ready for a test. Please try the 'opo' branch. There are a few new features around bindings in the branch along with the unix named socket support. The `bind_test.rb` test file should help with an example of the configuration.

**Comment by ohler55** [comment]
I'd like to release Agoo with the new binding features this weekend. Do you think you can try Agoo with ngnix before then?

**Comment by bryanp** [comment]
I should be able to give it a try tomorrow.

**Comment by bryanp** [comment]
Works great in my limited test. However, it still doesn't quite solve the problem. The reason I've used this approach with Puma is in situations where I don't want to specify a port to run the server. With Agoo, it looks like I'd still need to pass a port to `init`.

**Comment by ohler55** [comment]
I need to update the docs. I did not want to change the API so if you set the port to 0 it will be ignored and only the bind options used instead. You can do both or multiple binds as well.

**Comment by ohler55** [comment]
Great, I'll update the docs and release tonight. Thanks.

**Comment by ohler55** [comment]
With the release out, can this be closed?

**Comment by bryanp** [comment]
I think so. Thanks for implementing this!

**Comment by ohler55** [comment]
Always glad to add new features. Feedback is welcome as well.
