### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ohler55/agoo#32]
I would like to point out that identifiers like “[`__AGOO_TEXT_H__`](https://github.com/ohler55/agoo/blob/43df6048ea69395c03770871cef88a988557ca0b/ext/agoo/text.h#L3 "Update candidate")” and “[`_Hook`](https://github.com/ohler55/agoo/blob/b455db6a8caa15d870ff6b033f820ff1e07dc0f6/ext/agoo/hook.h#L24 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ohler55** [comment]
I guess I need to become more modern. When I first started C the format I used was common. Times change. I’ll makes the changes in the next branch merge. I’ve got a new feature I’m working on that touches a lot of files. (GraphQL)

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by ohler55** [comment]
What particular case or cases are you referring to?

**Comment by elfring** [comment]
I recommend to [rename some identifiers in affected source files](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by ohler55** [comment]
Other than the struct names which I will change, I don't see the need to not have variable that start with `to`, `is`, or `str`. Those are too common to avoid. I don't think there were any other offending names though.

**Comment by elfring** [comment]
Would you like to [reduce the tampering with the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers")?

**Comment by ohler55** [comment]
If you point out the offending variables I'll change them on a case by case basis. I can imagine that the words like `total` or `street` would be considered reserved but I don't see a need to change words such as those.

**Comment by elfring** [comment]
Please delete misplaced underscores from affected identifiers (as in the reported examples).

**Comment by ohler55** [comment]
Already started.

**Comment by elfring** [comment]
I wondered about your interpretation of reserved words. Was a bit more time needed for the understanding of desired naming conventions?

**Comment by ohler55** [comment]
Name restrictions such as https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html are too extreme in my opinion. In any case, I checked in code that no longer has the `__` character sequence nor the `_X` pattern. The code is in the `develop` branch and will be in the next release.

**Comment by ohler55** [comment]
Release 2.5.6 no longer uses restricted C names.

**Comment by ohler55** [comment]
Okay to close this?

**Comment by elfring** [comment]
I am curious if more identifiers will be renamed also in source files for other software.

**Comment by ohler55** [comment]
Yes, they will. Once project at a time. :-)
