### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ohler55/agoo#46]
[Two extra null pointer checks are not needed](https://github.com/ohler55/agoo/blob/868c013abaae643eee734fca7a04733795eb1426/ext/agoo/debug.c#L233 "Do I need to check for null before AGOO_FREE(p)?") in [the function “loop”](https://github.com/ohler55/agoo/blob/abe1577247bd2d311c5533ab56a9d4156696170f/ext/agoo/log.c#L330 "Update candidate").

**Comment by ohler55** [comment]
Good catch, thank you.

**Comment by ohler55** [comment]
I'll search for additional occurrences too.

**Comment by ohler55** [comment]
Found a few more and fixed them as well.
