### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [ohler55/agoo#48]
The function “[exit](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[sig_handler](https://github.com/ohler55/agoo/blob/580ea98709fd18de36faf443238dc04f4a24743f/ext/agoo/agoo.c#L80 "Update candidate")”.

**Comment by ohler55** [comment]
Thanks. Just pushed a fix to use `_exit` instead.

**Comment by elfring** [comment]
Are there any more function calls to reconsider according to the desired asynchronous-signal-safety?

**Comment by ohler55** [comment]
That is the only signal handler in the app.

**Comment by elfring** [comment]
This implementation contains still four function calls which I find suspicious.

**Comment by ohler55** [comment]
I think I misunderstood what you were commenting on. You are suggesting that the handle code is not thread safe. A valid point. I'll fix that.

**Comment by elfring** [comment]
Thread safety is different from safety concerns because of asynchronous signal handling.

**Comment by ohler55** [comment]
Pushed a change.

**Comment by ohler55** [comment]
How about this one. Can it be closed?

**Comment by elfring** [comment]
I hope that the software adjustments for this issue will be sufficient for a while.

**Comment by ohler55** [comment]
Thanks you.
