### ISSUE TITLE
Worker count when using rackup?

### ISSUE THREAD

**Issue by tomas** [ohler55/agoo#49]
Hi, great work with agoo!

I'm trying to fire the server through `rackup` (using a regular config.ru) but I'm not sure how to set the number of workers. I tried putting something like this on the config.ru file itself:

`Agoo::Server.init(6471, 'root', thread_count: 8, worker_count: 4)`

But no workie. How do I accomplish this?

**Comment by ohler55** [comment]
Use the `rackup` option `-O NAME[=VALUE]`. So for a worker count of 2 you would do something like this:

`$ rackup -r agoo -s agoo -O wc=2`

**Comment by tomas** [comment]
Gotcha. And thanks for the quick response!

By the way, I forked your repo to fix a few [compilation issues](https://github.com/ohler55/agoo/compare/develop...tomas:develop). If you're interested I can submit a PR.

**Comment by ohler55** [comment]
By all means. I use a C11 compiler so miss some of those. If you have them covered a fix would be really helpful.

**Comment by tomas** [comment]
Great! Will do.

By the way, does agoo support a) listening on a unix socket, and b) hot restarts? (Via USR2 or some other method)

**Comment by ohler55** [comment]
It does support unix sockets. Checkout the `bind_test.rb` file.

Agoo does not support hot restarts today. On the plus side it starts pretty fast. :-)

**Comment by tomas** [comment]
I see. So unix socket not possible via rackup, right? (Couldn't find anything related to it on the [rack handler](https://github.com/ohler55/agoo/blob/develop/lib/rack/handler/agoo.rb) definition)

**Comment by ohler55** [comment]
Good point. I can add that. If you want to open an issue for that I'll use that for the addition.

I'm curious, `rackup` introduces a lot over overhead. What are your reasons for using it?

**Comment by tomas** [comment]
I actually don't use the `rackup` command regularly. I've always just fired `puma` or `unicorn` directly, and have them read the config.ru file and start serving. The only reason I'm using it now is because I'm testing agoo in some of my apps, and want to be able to swap one for another without too much fuss.

I'm not sure what your reasons are not to do it that way, but I think supporting config.ru from the `agoo` command might make adoption easier.

**Comment by ohler55** [comment]
I suppose Agoo could look at the file suffix and if a `.ru` it could assume it is rack. That would be easy enough.

**Comment by tomas** [comment]
;)

**Comment by ohler55** [comment]
Created issue #50 and #51.

**Comment by ohler55** [comment]
I'll put something up for both those issues in the next few days. You comments would be appreciated.
