### ISSUE TITLE
Auto run config.ru files

### ISSUE THREAD

**Issue by ohler55** [ohler55/agoo#51]
Have Agoo run `<filename>.ru` files as rack but defining the `run` kernel method.

**Comment by ohler55** [comment]
Instead of adding the kernel level `run` it might be better to have a command line argument that add the kernel level `run` method. @tomas what do you think?

**Comment by tomas** [comment]
IMHO the user should just type `agoo` and boom, it should work. Why do you think it should require a command line argument?

**Comment by ohler55** [comment]
My concern was in assuming Agoo owns the kernel space enough to block others from using the `run` method. I probably shouldn't worry about it as that seems to be a general Ruby practice.

**Comment by ohler55** [comment]
I should have noted you expect to just type `agoo` and not `ruby -r agoo config.ru`. Simply `agoo` would be easy with no conflicts.

**Comment by tomas** [comment]
Oh yes. Ideally not even `bundle exec agoo`, but I know that's another story. :)

**Comment by ohler55** [comment]
Release 2.8.1 has the feature or fix.

**Comment by tomas** [comment]
Great! Thanks @ohler55

**Comment by tomas** [comment]
Just tried it, works great @ohler55. 

By the way, is there a reason why you're not evaluating `config.ru` in the context of a `Rack::Builder` block? (Like other servers do) 

Normally my basic `config.ru` files look like this:

```
require './boot'
map '/admin' { run Admin }
map '/' { run Website }
```

This is obviously not necessary, but again, I think it would make the transition to Agoo a bit easier. :)

**Comment by ohler55** [comment]
No reason other than I was not aware that was the common use pattern. I'll look at adding that.

**Comment by tomas** [comment]
Great!

**Comment by ohler55** [comment]
Where is `map` defined? I don't see it.

**Comment by tomas** [comment]
`map` is available as part of the Rack::Builder block, i.e.:

```
require './boot'

app = Rack::Builder.new do
  map '/admin' { run Admin }
  map '/' { run Website }
end

run app # optional
```

`boot.rb` contains the app definitions, i.e.:

```
require 'sinatra/base'

class Admin < Sinatra::Base
  get '/' { "hello admin" }
end

class Website < Sinatra::Base
  get '/' { "hello user" }
end
```

**Comment by ohler55** [comment]
Great, thanks.

**Comment by ohler55** [comment]
Check out the `rack-builder` branch please.

**Comment by ohler55** [comment]
Does this work for you?

**Comment by tomas** [comment]
Yes sir!

**Comment by ohler55** [comment]
Cool, I'll prepare a release.

**Comment by tomas** [comment]
Great! I'll submit a PR with the compilation fixes I did.

**Comment by ohler55** [comment]
I believe this can be closed.

**Comment by tomas** [comment]
I believe this too. :)
