### ISSUE TITLE
HTTP 103 Early Hints

### ISSUE THREAD

**Issue by evanleck** [ohler55/agoo#52]
Just curious if support for early hints is planned?

**Comment by ohler55** [comment]
Not planned yet. There is nothing stopping an application from returning a 103 though. How would you envision the use case?

**Comment by evanleck** [comment]
The use-case I envision is a Rack application that plans to include some CSS and JS via `<style>` and `<script>` (normal stuff) using early hints to tell the browser to start downloading those files before the full response has been rendered. As I understand it, that's the primary use-case for early hints.

I can't find anything official in the Rack repository, but there's some support across Ruby projects that I've linked to below, as well as the RFC. The Puma PR may be the most interesting.

- [Here's the RFC](https://tools.ietf.org/html/rfc8297).
- [Here's the merged PR](https://github.com/puma/puma/pull/1403) to Puma.
- [Here's the corresponding Rails PR](https://github.com/rails/rails/pull/30744) adding support to Rails.
- I guess Passenger is [still thinking about it](https://github.com/phusion/passenger/issues/2047).
- [Falcon](https://github.com/socketry/falcon) evidently supports it, though I've never used it.

I think the biggest difference between real early hints and just returning a 103 is that a single request would produce 2 responses: one 103 with early hints `Link` headers and the other with the full response (e.g. from a Rack application).

**Comment by ohler55** [comment]
Okay, its a feature that might go into the rack spec in the future. Lets leave this issue open for now and time permitting and a bit more research into rack plans and then it will get done.

**Comment by evanleck** [comment]
Sounds good, thank you!

**Comment by ianks** [comment]
We are currently using nginx with the http2_push_preload directive. This will turn Link headers into push promises. This is a much simpler and more compatible mechanism than sending a 103 IMO

http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_push_preload

**Comment by evanleck** [comment]
@ianks that's really cool, thanks for the info! I didn't even know Nginx could do that to be honest. I don't have direct access to the reverse proxy's configuration file so I can't do that myself, but it's definitely good to know.

**Comment by ianks** [comment]
Highly suggest it. Much easier to setup than h2o

**Comment by ohler55** [comment]
Please try the `early_hints` branch. There is a unit test for the new feature.

**Comment by ohler55** [comment]
Merged into develop branch.

**Comment by ksr-13** [comment]
How do I enable early hints for agoo? I am trying to use agoo with Hanami 2.0.

**Comment by ohler55** [comment]
```ruby
Agoo::Server::rack_early_hints(true)
```

Take a look at the test/early_hints_test.rb file.
