### ISSUE TITLE
TypeError: no implicit conversion of Agoo::ErrorStream into String

### ISSUE THREAD

**Issue by tomas** [ohler55/agoo#54]
The Rack::CommonLogger middleware initializer calls `::Logger.new(env[RACK_ERRORS])`, but env[RACK_ERRORS] doesn't seem to respond to `to_s`, raising this TypeError.

```
./lib/ruby/2.5.0/logger.rb in initialize
     File.open(filename, (File::WRONLY | File::APPEND))
./lib/ruby/2.5.0/logger.rb in open
     File.open(filename, (File::WRONLY | File::APPEND))
./lib/ruby/2.5.0/logger.rb in open_logfile
     File.open(filename, (File::WRONLY | File::APPEND))
./lib/ruby/2.5.0/logger.rb in set_dev
     @dev = open_logfile(log)
./lib/ruby/2.5.0/logger.rb in initialize
     set_dev(log)
./lib/ruby/2.5.0/logger.rb in new
     @logdev = LogDevice.new(logdev, :shift_age => shift_age,
./lib/ruby/2.5.0/logger.rb in initialize
     @logdev = LogDevice.new(logdev, :shift_age => shift_age,
./lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/logger.rb in new
     logger = ::Logger.new(env[RACK_ERRORS])
./lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/logger.rb in call
     logger = ::Logger.new(env[RACK_ERRORS])
./lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb in call
     status, header, body = @app.call(env)
```

**Comment by ohler55** [comment]
That actually brings up two issue. The Rack spec say the error stream should be on `env["rack.errors"]` unless my reading of the spec is way off. That might be okay if the value of the `RACK_ERRORS` is `"rack.errors"`. Is it?

Second, the spec says the only methods needed on the error stream are `puts`, `write`, `flush`, and `close`. From you description it sounds like the Rack logger expects a `to_s` also. What does the rack logger normally return? Anything other than something like `#<Foo:0x00007ff59d801e80>`?

**Comment by tomas** [comment]
Don't know. Rack::Logger simply calls `Logger.new(env[RACK_ERRORS])`. Shouldn't the Ruby Logger class detect that the passed object isn't a file but a stream?

**Comment by ohler55** [comment]
You would think so. I'll add a `to_s` that looks like the standard Ruby `to_s` and maybe you can see if things work.

**Comment by tomas** [comment]
I think I found the what's going on:

```
  class LogDevice
    def set_dev(log)
      if log.respond_to?(:write) and log.respond_to?(:close)
        @dev = log
      else
        @dev = open_logfile(log)
        @dev.sync = true
        @filename = log
      end
    end
  end
```

**Comment by ohler55** [comment]
I'll have that fixed tonight. Thanks.

**Comment by ohler55** [comment]
Had a slow moment so made the fix. It is in the `close` branch if you would like to try it.

**Comment by ohler55** [comment]
Does this work for you?

**Comment by tomas** [comment]
Indeed it does. Thanks @ohler55!
