### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by mblumtritt** [ohler55/agoo#56]
I'd like to know if there's a road map.

- What is planned next?
- Is IPv6 on the list?
- Where do you need support? 

Great work by the way!

**Comment by ohler55** [comment]
As a matter of fact I do. It is negotiable though. As for IPv6, that is already supported.

1. GraphQL subscriptions.
2. TSL (HTTPS)
3. GraphQL Connections (paging)

**Comment by ohler55** [comment]
I should have answered your last question. I need feedback! Whats missing in particular. Someone using Agoo or even some more advanced examples.

**Comment by s0kil** [comment]
Are you still planning on supporting HTTP/2? Or even HTTP/3?

**Comment by ohler55** [comment]
HTTP/2 is next on the feature list. HTTP/3 is not even on the radar yet. It will be when it is supported by more than just the chrome browser though.

**Comment by dalisoft** [comment]
@ohler55 
Let users choose HTTP versions, it's will be very great feature, like this ` httpVer: 1 // available values 1.1, 2, 3 `
But not important or critical currently as we can use `nginx` as reverse-proxy and `nginx` does this for us, but, native solution always will be better and performant :)

**Comment by ohler55** [comment]
With HTTP/2 support there will be a choice. I've got a few things on my plate right now so it will be a little longer before I get the HTTP/2 support.

**Comment by dalisoft** [comment]
@ohler55 It's not critical now, i think in future will be

**Comment by fastengineer** [comment]
Please create a page on https://opencollective.com/opensource

**Comment by petermumford** [comment]
Are there any plans to create a schema generator to create a file for Agoo to load in from when using the `Agoo::GraphQL.load_file()` method?
