### ISSUE TITLE
Second option in handler call method

### ISSUE THREAD

**Issue by JonathanWThom** [ohler55/agoo#58]
I'm curious what the empty hash within a handler's `#call` method does. Clearly the first and last elements are response code and body, but I couldn't figure out what possible options could be passed to the `{}`. I dove into the source of `Server#handle`, but unfortunately couldn't get it figured out.

```
class MyHandler
  def call(req)
    [ 200, { }, [ "hello world" ] ]
  end
end
```

This isn't really an "issue," but I wasn't sure where else to ask it. Sorry if the answer is obvious : )

**Comment by ohler55** [comment]
The easy answer is a link. https://rack.github.io

**Comment by JonathanWThom** [comment]
Headers, of course! Thank you.
