### ISSUE TITLE
GraphQL with rack?

### ISSUE THREAD

**Issue by HorizonShadow** [ohler55/agoo#60]
The GraphQL example starts its own server. I'm wondering if I can stick something in a `config.ru` file to accomplish the same thing.

```ruby
require 'agoo'


map '/graphql' { run Agoo::GraphQL(some_schema) }

```
Or something

**Comment by ohler55** [comment]
If I understand correctly you would like to see something like the `example/graphql/app.rb` but be able to start with Rack. Is that correct?

**Comment by HorizonShadow** [comment]
I don't see a `example/grahpql/app.rb`, so I'm not sure.

If you mean the one in the readme, then yes.

**Comment by ohler55** [comment]
oh, my mistake. My local copy only. Let me clean up and push. If you are looking for a `config.ru` file let me see if I can propose something.

**Comment by ohler55** [comment]
Push `app.rb` to the develop branch. It looks like I'll have to make a change or two to use just a `config.ru` file. I'll get that started though.

**Comment by ohler55** [comment]
I was trying to come up with some way to keep the configuration all in the `config.ru` file but finally settled on having the rackup invocation use the `-O` option. In the rack branch there is a new example in `example/graphql/config.ru`. The command to run assuming you want to use the local code for testing is `rackup -I ../../ext -I ../../lib -r agoo -s agoo -Ographql=/graphql`. Let me know if you have any suggested changes or additions. I'll wait for your feedback before releasing.

**Comment by HorizonShadow** [comment]
I don't know how the underlying systems work, but I would expect to do something like

```rb
# config.ru
map('/graphql') { run Agoo::Graphql.app }
```

Looking through the examples, it looks like the graphql server is actually integrated with Agoo::Server, so maybe that's not possible.

**Comment by ohler55** [comment]
Yes, the graphql server is integrated into the server.

**Comment by ohler55** [comment]
Does the approach taken seem reasonable to you as a Rack user?

**Comment by HorizonShadow** [comment]
Should be fine. Every server has their own way of leveraging rack.

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
No complaints, closing.

**Comment by robotex82** [comment]
I hope it is ok to reopen this issue.

I have been thinking about using the graphQL implementation in a Rails app. To do this I'll have to mount a graphQL schema inside the rails routes as a rack app:

`
Rails.application.routes.draw do
  mount Agoo::GraphQL.schema(Schema.new), at: '/graphql'
end
`

Could this be possible?

My goal would be to write an extensible schema for an existing ruby on rails cms.

**Comment by ohler55** [comment]
Better to create a separate issue. There might be a better way to set up the routes than using the rails router. We can discuss to make sure I'm not missing something.

**Comment by robotex82** [comment]
Ok, thanks! I just opened #93
