### ISSUE TITLE
How does agoo talk to rails?

### ISSUE THREAD

**Issue by wade-welles** [ohler55/agoo#76]
I have read over the code over and over and have been cutting things down to make a simpler version but I don't see how its talking to rails. 

For example, when thin talks to rails it requires the dispatch package. But I don't see anything like that in the code. Can you explain that or point the code that specifically talks to rails to build the page that is handed to the client? 

Thanks

**Comment by ohler55** [comment]
Agoo supports Rack and Rails uses Rack. Agoo does not need any direct calls into Rails other that `#call` made when a request arrives. I have not looked at the code for thin so I can't comment about that.

**Comment by wade-welles** [comment]
Using the method `call` provided by rack generates the rails html and you are doing this in `rhook.c` by adding the call method to your handler object? 

I get a major speed boost when using this so I had assumed you moved rack logic into your C code to avoid using ruby. 

Thanks for your time and assistance in helping people understand your project. Its very cool.

**Comment by ohler55** [comment]
Glad you like the project. Its nice to get feedback.

The big speedup come from the general request handing, especially static assets. Those never have to see rails at all if set up correctly.

The hooks are what handle each request. Different ones for different handlers. Also take a look at request.c. That does the setup for the call.

**Comment by wade-welles** [comment]
Great, I will close this.  Thanks for explaining more of the details, it really helps elucidate the server. It has a lot of features so pulling out the basic functionality can be difficult when  I'm getting back into C. Thanks again for making this.

**Comment by wade-welles** [comment]
Could you be more speciifc about what static assets you are referring to? And where in the code? Is it essentially caching it?

**Comment by ohler55** [comment]
Static assets are any pages that do not have to be generated. Like images, style sheets, javascript, or straight HTML. You specify a root for Agoo you multiple source for pages. The code in in con.c and page.c.
