### ISSUE TITLE
log.c:454:21: error: storage size of ‘tz’ isn’t known

### ISSUE THREAD

**Issue by wade-welles** [ohler55/agoo#77]
Most recent pushes have an error with timezone in dtime component.

**Comment by ohler55** [comment]
What OS does the problem occur on? That code hasn't changed in a long time. Travis has been having issues with OSX recently but that is a travis issue. A rebuild shows Travis has worked out those issues.

**Comment by ohler55** [comment]
Are you still interested in this issue? I will need more information to proceed.
