### ISSUE TITLE
Compiling on alpine 

### ISSUE THREAD

**Issue by waghanza** [ohler55/agoo#79]
Hi @ohler55,

Trying to install on `alpine`, I have

~~~
dtime.c:11:31: error: 'CLOCK_REALTIME' undeclared (first use in this function); did you mean 'CLOCK_REALTIME_COURSE'?
 #define CLOCK_REALTIME_COURSE CLOCK_REALTIME
~~~

while using `gem install agoo`

I'm on 
+ `ruby` **2.6**
+ `gem` **3.06**

Regards,

----------
edit : maybe related to https://github.com/ohler55/agoo/issues/14

**Comment by ohler55** [comment]
That is odd. Was that the only error or were there complaints about missing header files as well?

**Comment by waghanza** [comment]
This the only missing thing in https://github.com/the-benchmarker/web-frameworks/pull/1968.

I have update the full log in https://gist.github.com/bedc4fb00ab91574fb91b53958214ba5

+ Alpine Linux 3.10
+ gcc (Alpine 8.3.0) 8.3.0

**Comment by ohler55** [comment]
Thanks. Has something changed since the last time? It looks like the headers are no longer the same and no longer POSIX.

**Comment by ohler55** [comment]
Which PR was that. I saw 6 but didn't know which was relevant.

**Comment by ohler55** [comment]
Doing a little research it looks like Alpine might need the use of either `-D_POSIX_SOURCE` or maybe a `#define _POSIX_C_SOURCE 199506L` I'll do some experimenting with docker.

Can you verify that you've done something like this:

```
RUN apk update
&& apk add --virtual build-dependencies
build-base
```

**Comment by waghanza** [comment]
seems to be the same with the docker line you gave me

I also see the `#define _POSIX_C_SOURCE 199506L` source when searching around on stackoverflow, but I have no `C` skill to `PR` :stuck_out_tongue:

**Comment by ohler55** [comment]
I pulled your branch and did a docker build with no errors. Of course the Dockerfile generated `FROM ruby:2.6`. What should I use to get the failure you are seeing?

**Comment by waghanza** [comment]
Run 
```
shards install
shards build
bin/make config
```
This should create a `Dockerfile` in `ruby/agoo`.

The idea is that this error occurred on `bundle install`. If you run into the container, (with this line and after commented), you will see the compilation error

**Comment by ohler55** [comment]
okay, will try from in the container. I'll try Sunday. Traveling today.

**Comment by ohler55** [comment]
I'm not sure what the difference is but even from in the container I don't see any build errors. The Dockerfile is using the ruby:2.6 image. Is that the same for you? I used the `use_alpine` branch but can't seem to make it fail.

**Comment by waghanza** [comment]
Ah sorry, yes.

The official image use **Debian** but I want to switch to **alpine** since less heavy

**Comment by ohler55** [comment]
Right, so where can I find the alpine images or get them hooked into the shard/neph build environment?

**Comment by ohler55** [comment]
So, if I don't use the neph stuff and just go for a custom Dockerfile from `ruby:2.6.5-alpine` I do get errors indicating the build environment isn't there. If that is the correct starting point I'll see what has to be added to make it work.

**Comment by ohler55** [comment]
This worked for me with a change in Agoo to put in two compile directives.
```
FROM ruby:2.6.5-alpine

WORKDIR /usr/src/app

COPY . ./

RUN apk add --update build-base

RUN bundle install --without development test

ENV AGOO_WORKER_COUNT $(nproc)

CMD ruby app.rb
```

I suspect Aggo-C will need the same directives.

I would like to update the apps for both as well to match some changes in the graphql-benchmarks. @waghanza , I put you as a reviewer. Anyway if you would like me to make the changes on your fork, let me know and I can branch as long as I am a collaborator..

**Comment by waghanza** [comment]
Sure, go on. :heart:

**Comment by ohler55** [comment]
PR is ready for you.
