### ISSUE TITLE
`require': uninitialized constant StringIO (NameError)

### ISSUE THREAD

**Issue by Juksefantomet** [ohler55/agoo#80]
Hello,

Just to clarify on the issue that occurs on newer versions of ruby 2.6.x in this case.

stringio is not loaded by default on later versions causing 'agoo' to fail when running example code for 'rack'

this can be solved by simply

replacing
```
     require 'agoo'
```

with
```
     require 'stringio'
     require 'agoo'
```

make sure the load order is correct as agoo will fail if stringio is not loaded in advance.

**Comment by ohler55** [comment]
Thanks. I'll get that updated tonight.

**Comment by waghanza** [comment]
I've detected this issue on `ruby` **2.7** only

**Comment by waghanza** [comment]
@Juksefantomet where do you have this issue ?

**Comment by Juksefantomet** [comment]
This occured on ruby 2.6.3 - On my work desktop running Antergos (Arch Distro), specifically with bundler 2.0.1 under bundler config set path 'vendor/bundle' initially but also confirmed unning globally installed gems defaulted via home enviroment. @waghanza

**Comment by ohler55** [comment]
I added the require anyway as it does not cause a problem for older version and is needed for at least Ruby 2.7.0. Prepping for a release now.

**Comment by ohler55** [comment]
Pushed a release.

**Comment by waghanza** [comment]
@Juksefantomet is this solved you issue ? we shall close, if yes

**Comment by Juksefantomet** [comment]
Hello :smile: 

Yes this resolved the issue. Had to get back to work and on my actual environment experiencing the issue to confirm.

After installing the bumped version i no longer require the manual requirement of stringio.

Thanks!
