### ISSUE TITLE
Hook before graphql request is handled

### ISSUE THREAD

**Issue by JonasBorchelt** [ohler55/agoo#86]
Hey,

is it possible to apply a hook like
```
Agoo::GraphQL.build_headers
```
not for the response but for the request? To be able to check the request headers and decide to continue to proceed the request or to block/redirect it?

**Comment by ohler55** [comment]
That functionality already exists but in a slightly different manner. The resolver method implemented by the ruby object can take not arguments, a single argument, or 2 arguments. Zero is obvious. If one argument the argument is a Hash of the arguments passed from GraphQL. If two then the second argument is the request itself. The request is the same as used by the Rack call() function, agoo.Request.

If you have some ideas about improving the documentation I would gladly incorporate those suggestions or even entertain a pull request if you feel so inclined.

**Comment by JonasBorchelt** [comment]
E.g.: To check if the token is valid of the request, I have to check in every type function again if it's  valid. If I would be able to check before even the graph parsing will start, it would be much better.

**Comment by ohler55** [comment]
So, pre-graphql checker, right? That could certainly be added but realize it would only not be compatible with any other server. Does that sound okay?

**Comment by ohler55** [comment]
Are you still interested in seeing this addition? Did my proposed solution should reasonable?

**Comment by JosimarCamargo** [comment]
Just sharing some thoughts here, the feature of having an hook before(and maybe after) the graphQL request would help me to DRY some code, but the same can be done with pure ruby and also with some gems eg:, https://stackoverflow.com/questions/23444964/is-it-possible-to-do-a-before-action-in-ruby-like-in-rails , so I'll let you guys decide if the feature must be added to Agoo

About broke compatibility with others server worry me a little, this means broke compatibility with rails ? It would not be possible use Agoo graphql and rails on the same application?

**Comment by ohler55** [comment]
When I said the feature would not be compatible with other servers I mean that you should not expect code specific to Agoo to work with other servers. I did not mean it would break anything in rails.

**Comment by JosimarCamargo** [comment]
Now I get it, thanks

**Comment by JonasBorchelt** [comment]
Hey Peter,

I'm very sorry! I don't know why I didn't see your message. Yes, such a feature would be awesome. For query and mutations a hook where you can even add something to the request header, like a user object. Means request->preprocess hook[be even able, if something went wrong or not a valid token, to response with http code and body]->query/mutation/rest endpoint 

For queries/rest endpoints you can already have args and request as parameter, which is nice. 

Thank you for your time.

**Comment by ohler55** [comment]
Back burner until after the new year.

**Comment by ohler55** [comment]
Would the solution for issue #112 satisfy your requirements?

**Comment by ohler55** [comment]
No response. Closing issue as an option now exists to handle the original request.

**Comment by JonasBorchelt** [comment]
Hey Peter,

seems this is for every query and every mutation. This is already working. I would like to have something general. That I don't have to take care at every query.
