### ISSUE TITLE
How to create a dynamic GraphQL schema

### ISSUE THREAD

**Issue by JosimarCamargo** [ohler55/agoo#95]
Hello, I'm creating a GraphQL API with Agoo(with has been really awesome), within a scenario where each user can have his own types, I was wondering if there is some way to create and load those types, based on the request headers?

**Comment by ohler55** [comment]
There is not currently a way to do what you describe directly. The GraphQL engine is current linked to a server so it is no possible to have multiple engines for a single server. The only way I can think of to do that right now would be to spin up a different server for a user when they log in. If you have a small number of users that might not be an issue. If you have hundreds all accessing at the same time it might be too much.

**Comment by JosimarCamargo** [comment]
That is sad news, my company was rewriting our GraphQl API with Agoo, due to high performance, and how we have several clients and they can create their own types, a GraphQL API that allow to us create types on the flight is a must have to us. Please don't take this bad, you are doing a really awesome work here, thanks for all support.

**Comment by ohler55** [comment]
There are some possibilities to create types on the fly we could discuss. Keeping them separate is not currently supported though.

**Comment by JosimarCamargo** [comment]
I'll talk with my teammates about it, thanks again

**Comment by VojislavVlasic** [comment]
Hello @ohler55, hope you're doing well.
Just to check in with you, does agoo support dynamic GraphQL schema creation now by any chance?
