### ISSUE TITLE
Configuring worker count and thread count when used with Rails

### ISSUE THREAD

**Issue by vitobotta** [ohler55/agoo#96]
Hi! The README shows the command `rails server -u agoo` for Rails, but how do I configure worker/thread counts in this case? Thanks a lot, this gem looks super cool!

**Comment by vitobotta** [comment]
Just seen this page https://github.com/ohler55/agoo/blob/370e72fd0ad5df595589c8a45062bb8684123510/misc/rails.md

So for the workers I can use `-O wc=N` but for the threads?

**Comment by vitobotta** [comment]
The app starts with rackup but I am getting `env variable SERVER_PORT has non-string value nil` when I view a page. I don't get the error with `rails server -u agoo` but how do I set workers and threads in this case? Thanks and sorry for the many questions :)

**Comment by ohler55** [comment]
You can always use the other command line options once you specify using agoo. Some of the options are:

 * port
 * root or dir
 * workers or wc
 * graphql
 * silent
 * verbose
 * debug
 * bind
 * log_dir
 * log_classic
 * log_console
 * log_colorize

**Comment by ohler55** [comment]
Agoo does not check environment variables so SERVER_PORT would be ignore but Rails may look at that if a port is not specified.

**Comment by ohler55** [comment]
Is there a reason to keep this open?
